USE [GD1C2022]
GO

-- Crea el Esquema LUSAX2
CREATE SCHEMA [LUSAX2]
GO

-- Crea la Tabla "Telemetria" con una CONSTRAINT identificada PK_TELE_ID
CREATE TABLE [LUSAX2].[Telemetria] (
  TELEMETRIA_ID int NOT NULL IDENTITY(1,1),
  TELE_AUTO_ID int,
  Carrera_id int,
  SECTOR_CODIGO int,
  TELE_CAJA_CAMBIO_ID int,
  TELE_MOTOR_ID int,
  CONSTRAINT PK_TELE_ID PRIMARY KEY (TELEMETRIA_ID),
);

-- Crea la Tabla "Telemetria_Auto" y la Constraint para su Primary Key
CREATE TABLE [LUSAX2].[Telemetria_Auto] (
  TELE_AUTO_ID int NOT NULL,
  AUTO_ID int,
  TELE_AUTO_POSICION decimal(18,0),
  TELE_AUTO_NRO_VUELTA decimal(18,0),  
  TELE_AUTO_DISTANCIA_CARRERA decimal(18,6),
  TELE_AUTO_TIEMPO_VUELTA decimal(18,10),
  TELE_AUTO_VELOCIDAD decimal(18,2),
  TELE_AUTO_COMBUSTIBLE decimal(18,2),
  TELE_AUTO_DISTANCIA_VUELTA decimal(18,2),
  CONSTRAINT PK_TELE_AUTO_ID PRIMARY KEY (TELE_AUTO_ID),
);

-- Crea la Tabla "Telemetria_Auto" y la Constraint para su Primary Key
CREATE TABLE [LUSAX2].[Automovil] (
  AUTO_ID INT NOT NULL IDENTITY(1,1),
  AUTO_NUMERO int NOT NULL,
  ESCUDERIA_NOMBRE nvarchar(255),
  PILOTO_ID int,
  AUTO_MODELO nvarchar(255),
  CONSTRAINT PK_AUTO_ID PRIMARY KEY (AUTO_ID),
);

-- Crea la Tabla "Carrera" y la Constraint para su Primary Key
CREATE TABLE [LUSAX2].[Carrera] (
  Carrera_id int NOT NULL IDENTITY(1,1),
  CARRERA_CODIGO int ,
  Circuito_id int,
  CARRERA_CLIMA  nvarchar(100),
  CARRERA_CANT_VUELTAS int,
  CARRERA_FECHA date,
  CARRERA_TOTAL_CARRERA DECIMAL(18,2),
  CONSTRAINT PK_Carrera_id PRIMARY KEY (Carrera_id),
);

-- Crea la Tabla "Circuito" y la Constraint para su Primary Key
CREATE TABLE [LUSAX2].[Circuito] (
  Circuito_id int NOT NULL IDENTITY(1,1),
  CIRCUITO_CODIGO int,
  CIRCUITO_NOMBRE nvarchar(255),
  CIRCUITO_PAIS nvarchar(255),
  SECTOR_CODIGO int,
  CONSTRAINT PK_Circuito_id PRIMARY KEY (Circuito_id),
);

-- Crea la Tabla "Sector" y la Constraint para su Primary Key
CREATE TABLE [LUSAX2].[Sector] (
  SECTOR_CODIGO int NOT NULL,
  SECTOR_TIPO nvarchar(255),
  SECTOR_DISTANCIA decimal(18, 2),
  CONSTRAINT PK_SECTOR_CODIGO PRIMARY KEY (SECTOR_CODIGO),
);

-- Crea la Tabla "Telemetria_CajaDeCambio" y la Constraint para su Primary Key
CREATE TABLE [LUSAX2].[Telemetria_CajaDeCambio] (
  TELE_CAJA_CAMBIO_ID int NOT NULL identity(1,1),
  CAJA_NRO_SERIE nvarchar(255),
  TELE_CAJA_TEMP_ACEITE decimal (18,2),
  TELE_CAJA_RPM decimal (18,2),
  TELE_CAJA_DESGASTE decimal (18,2),
  CONSTRAINT PK_TELE_CAJA_CAMBIO_ID PRIMARY KEY (TELE_CAJA_CAMBIO_ID),
);

-- Crea la Tabla "CajaDeCambio" y la Constraint para su Primary Key
CREATE TABLE [LUSAX2].[CajaDeCambio] (
  CAJA_NRO_SERIE nvarchar(255),
  CAJA_MODELO nvarchar (50),
  AUTO_ID INT,
  CONSTRAINT PK_CAJA_NRO_SERIE PRIMARY KEY (CAJA_NRO_SERIE),
);

-- Crea la Tabla "Telemetria_Freno" y la Constraint para su Primary Key
CREATE TABLE [LUSAX2].[Telemetria_Freno] (
  TELE_FRENO_ID int NOT NULL identity(1,1),
  FRENO_NRO_SERIE nvarchar(255),
  TELE_FRENO_GROSOR_PASTILLA decimal (18,2),
  TELE_TEMPERATURA decimal (18,2),
  TELE_TAMANIO_DISCO decimal (18,2),
  CONSTRAINT PK_TELE_FRENO_ID PRIMARY KEY (TELE_FRENO_ID),
);

-- Crea la Tabla "Freno" y la Constraint para su Primary Key
CREATE TABLE [LUSAX2].[Freno] (
  FRENO_NRO_SERIE nvarchar(255),
  FRENO_POSICION nvarchar(255),
  AUTO_ID INT,
  CONSTRAINT PK_FRENO_NRO_SERIE PRIMARY KEY (FRENO_NRO_SERIE),
);

-- Crea la Tabla "Telemetria_Neumatico" y la Constraint para su Primary Key
CREATE TABLE [LUSAX2].[Telemetria_Neumatico] (
  TELE_NEUMATICO_ID int NOT NULL identity(1,1),
  NEUMATICO_NRO_SERIE nvarchar(255),
  TELE_NEUMATICO_PRESION decimal(18,6),
  TELE_NEUMATICO_PROFUNDIDAD decimal(18,6),
  TELE_NEUMATICO_TEMPERATURA decimal(18,6),
  CONSTRAINT PK_TELE_NEUMATICO_ID PRIMARY KEY(TELE_NEUMATICO_ID),
);

-- Crea la Tabla "Escuderia" y la Constraint para su Primary Key
CREATE TABLE [LUSAX2].[Escuderia] ( 
  ESCUDERIA_NACIONALIDAD NVARCHAR (255),
  ESCUDERIA_NOMBRE nvarchar (255) NOT NULL,
  CONSTRAINT PK_ESCUDERIA_NOMBRE PRIMARY KEY(ESCUDERIA_NOMBRE),
);

-- Crea la Tabla "Piloto" y la Constraint para su Primary Key
CREATE TABLE [LUSAX2].[Piloto] (
  PILOTO_ID int NOT NULL IDENTITY (1,1),
  PILOTO_NOMBRE nvarchar(50),
  PILOTO_APELLIDO nvarchar(50),
  PILOTO_NACIONALIDAD nvarchar(50),
  PILOTO_FECHA_NACIMIENTO date,
  CONSTRAINT PK_PILOTO_ID PRIMARY KEY(PILOTO_ID),
);

-- Crea la Tabla "Telemetria_Motor" y la Constraint para su Primary Key
CREATE TABLE [LUSAX2].[Telemetria_Motor] (
  TELE_MOTOR_ID int IDENTITY(1,1),
  MOTOR_NRO_SERIE nvarchar(255),
  TELE_MOTOR_RPM decimal(18, 6),
  TELE_MOTOR_TEMP_ACEITE decimal(18, 6),
  TELE_MOTOR_TEMP_AGUA  decimal(18, 6),
  TELE_MOTOR_POTENCIA decimal(18, 6),
  CONSTRAINT PK_TELE_MOTOR_ID PRIMARY KEY(TELE_MOTOR_ID),
);

-- Crea la Tabla "Motor" y la Constraint para su Primary Key
CREATE TABLE [LUSAX2].[Motor] (
  MOTOR_NRO_SERIE nvarchar(255),
  MOTOR_MODELO nvarchar(255),
  AUTO_ID INT,
  CONSTRAINT PK_MOTOR_NRO_SERIE PRIMARY KEY(MOTOR_NRO_SERIE),
);

-- Crea la Tabla "Incidente" y la Constraint para su Primary Key
CREATE TABLE [LUSAX2].[Incidente] (
  INCIDENTE_ID  int  NOT NULL identity(1,1),
  CARRERA_id int,
  INCIDENTE_TIPO nvarchar(255),
  INCIDENTE_BANDERA nvarchar(255),
  INCIDENTE_TIEMPO decimal(18,2),
  CONSTRAINT PK_INCIDENTE_ID PRIMARY KEY(INCIDENTE_ID),
);

-- Crea la Tabla "AutoxIncidente" y la Constraint para su Primary Key
CREATE TABLE [LUSAX2].[AutoxIncidente] (
  INCIDENTE_ID int NOT NULL IDENTITY(1,1),
  AUTO_ID int NOT NULL,
  INCIDENTE_NUMERO_VUELTA decimal(18,0),
  CONSTRAINT PK_AutoXIncidente_ID PRIMARY KEY(AUTO_ID,INCIDENTE_ID),
);

-- Crea la Tabla "Parada" y la Constraint para su Primary Key
CREATE TABLE [LUSAX2].[Parada] (
  PARADA_CODIGO_BOX int NOT NULL identity(1,1),
  AUTO_ID int,
  Carrera_id int,
  PARADA_BOX_VUELTA decimal(18, 0),
  PARADA_BOX_TIEMPO decimal(18, 2),
  CONSTRAINT PK_PARADA_CODIGO_BOX PRIMARY KEY(PARADA_CODIGO_BOX),
);

-- Crea la Tabla "Neumatico" y la Constraint para su Primary Key
CREATE TABLE [LUSAX2].[Neumatico] (
  NEUMATICO_NRO_SERIE nvarchar(255),
  NEUMATICO_POSICION nvarchar(255),
  NEUMATICO_TIPO nvarchar(255),
  AUTO_ID INT,
  CONSTRAINT PK_NEUMATICO_NRO_SERIE PRIMARY KEY(NEUMATICO_NRO_SERIE),
);

-- Crea la Tabla "Cambio_Neumatico" y la Constraint para su Primary Key
CREATE TABLE [LUSAX2].[Cambio_Neumatico] (
  ID_CAMBIO_NEUMATICOS int NOT NULL identity(1,1),
  NEUMATICO_NRO_SERIE_VIEJO nvarchar(255),
  NEUMATICO_NRO_SERIE_NUEVO nvarchar(255),
  PARADA_CODIGO_BOX int,
  CONSTRAINT PK_ID_CAMBIO_NEUMATICOS PRIMARY KEY(ID_CAMBIO_NEUMATICOS),
);

-- Altera La Tabla "Parada" para que la FK referencie a una Campo de otra Tabla
ALTER TABLE [LUSAX2].[Parada]
ADD CONSTRAINT FKP_Carrera_id
FOREIGN KEY (Carrera_id) REFERENCES [LUSAX2].[Carrera](Carrera_id);

-- Altera La Tabla "Parada" para que la FK referencie a una Campo de otra Tabla
ALTER TABLE [LUSAX2].[Parada]
ADD CONSTRAINT FKP_AUTO_ID
FOREIGN KEY (AUTO_ID) REFERENCES [LUSAX2].[automovil](AUTO_ID);

-- Altera La Tabla "Cambio_Neumatico" para que la FK referencie a una Campo de otra Tabla
ALTER TABLE [LUSAX2].[Cambio_Neumatico]
ADD CONSTRAINT FKC_NEUMATICO_NRO_SERIE_NUEVO
FOREIGN KEY (NEUMATICO_NRO_SERIE_NUEVO) REFERENCES [LUSAX2].[Neumatico](NEUMATICO_NRO_SERIE);

-- Altera La Tabla "Cambio_Neumatico" para que la FK referencie a una Campo de otra Tabla
ALTER TABLE [LUSAX2].[Cambio_Neumatico]
ADD CONSTRAINT FKC_NEUMATICO_NRO_SERIE_VIEJO
FOREIGN KEY (NEUMATICO_NRO_SERIE_VIEJO) REFERENCES [LUSAX2].[Neumatico](NEUMATICO_NRO_SERIE);

-- Altera La Tabla "Cambio_Neumatico" para que la FK referencie a una Campo de otra Tabla
ALTER TABLE [LUSAX2].[Cambio_Neumatico]
ADD CONSTRAINT FKC_PARADA_CODIGO_BOX
FOREIGN KEY (PARADA_CODIGO_BOX) REFERENCES [LUSAX2].[Parada](PARADA_CODIGO_BOX);

-- Altera La Tabla "AutoxIncidente" para que la FK referencie a una Campo de otra Tabla
ALTER TABLE [LUSAX2].[AutoxIncidente]
ADD CONSTRAINT FKI_AUTO_ID
FOREIGN KEY (AUTO_ID) REFERENCES [LUSAX2].[Automovil](AUTO_ID);

-- Altera La Tabla "AutoxIncidente" para que la FK referencie a una Campo de otra Tabla
ALTER TABLE [LUSAX2].[AutoxIncidente]
ADD CONSTRAINT FK_INCIDENTE_ID
FOREIGN KEY ( INCIDENTE_ID) REFERENCES [LUSAX2].[Incidente](INCIDENTE_ID);

-- Altera La Tabla "Incidente" para que la FK referencie a una Campo de otra Tabla
ALTER TABLE [LUSAX2].[Incidente]
ADD CONSTRAINT FKI_Carrera_id
FOREIGN KEY (Carrera_id) REFERENCES [LUSAX2].[Carrera](Carrera_id);

-- Altera La Tabla "Telemetria" para que la FK referencie a una Campo de otra Tabla
ALTER TABLE [LUSAX2].[Telemetria]
ADD CONSTRAINT FK_TELE_AUTO_ID
FOREIGN KEY (TELE_AUTO_ID) REFERENCES [LUSAX2].[Telemetria_Auto](TELE_AUTO_ID);

-- Altera La Tabla "Telemetria" para que la FK referencie a una Campo de otra Tabla
ALTER TABLE [LUSAX2].[Telemetria]
ADD CONSTRAINT FK_Carrera_id
FOREIGN KEY (Carrera_id) REFERENCES [LUSAX2].[Carrera](Carrera_id);

-- Altera La Tabla "Telemetria" para que la FK referencie a una Campo de otra Tabla
ALTER TABLE [LUSAX2].[Telemetria]
ADD CONSTRAINT FK_SECTOR_CODIGO
FOREIGN KEY (SECTOR_CODIGO) REFERENCES [LUSAX2].[Sector](SECTOR_CODIGO);

-- Altera La Tabla "Telemetria" para que la FK referencie a una Campo de otra Tabla
ALTER TABLE [LUSAX2].[Telemetria]
ADD CONSTRAINT FK_TELE_CAJA_CAMBIO_ID
FOREIGN KEY (TELE_CAJA_CAMBIO_ID) REFERENCES [LUSAX2].[Telemetria_CajaDeCambio](TELE_CAJA_CAMBIO_ID);

-- Altera La Tabla "Telemetria" para que la FK referencie a una Campo de otra Tabla
ALTER TABLE [LUSAX2].[Telemetria]
ADD CONSTRAINT FK_TELE_MOTOR_ID
FOREIGN KEY (TELE_MOTOR_ID) REFERENCES [LUSAX2].[Telemetria_Motor](TELE_MOTOR_ID);

-- Altera La Tabla "Telemetria_Neumatico" para que la FK referencie a una Campo de otra Tabla
ALTER TABLE [LUSAX2].[Telemetria_Neumatico]
ADD CONSTRAINT FKN_NEUMATICO_NRO_SERIE
FOREIGN KEY (NEUMATICO_NRO_SERIE) REFERENCES [LUSAX2].[Neumatico](NEUMATICO_NRO_SERIE);

-- Altera La Tabla "Telemetria_Auto" para que la FK referencie a una Campo de otra Tabla
ALTER TABLE [LUSAX2].[Telemetria_Auto]
ADD CONSTRAINT FK_AUTO_ID
FOREIGN KEY (AUTO_ID) REFERENCES [LUSAX2].[Automovil](AUTO_ID);

-- Altera La Tabla "Automovil" para que la FK referencie a una Campo de otra Tabla
ALTER TABLE [LUSAX2].[Automovil]
ADD CONSTRAINT FK_ESCUDERIA_NOMBRE
FOREIGN KEY (ESCUDERIA_NOMBRE) REFERENCES [LUSAX2].[Escuderia](ESCUDERIA_NOMBRE);

-- Altera La Tabla "Automovil" para que la FK referencie a una Campo de otra Tabla
ALTER TABLE [LUSAX2].[Automovil]
ADD CONSTRAINT FK_PILOTO_ID
FOREIGN KEY (PILOTO_ID) REFERENCES [LUSAX2].[Piloto](PILOTO_ID);

-- Altera La Tabla "NEUMATICO" para que la FK referencie a una Campo de otra Tabla
ALTER TABLE [LUSAX2].[NEUMATICO]
ADD CONSTRAINT FKn_AUTO_ID
FOREIGN KEY (AUTO_ID) REFERENCES [LUSAX2].[AUTOMOVIL](AUTO_ID);

-- Altera La Tabla "CAJADECAMBIO" para que la FK referencie a una Campo de otra Tabla
ALTER TABLE [LUSAX2].[CAJADECAMBIO]
ADD CONSTRAINT FKc_AUTO_ID
FOREIGN KEY (AUTO_ID) REFERENCES [LUSAX2].[AUTOMOVIL](AUTO_ID);

-- Altera La Tabla "FRENO" para que la FK referencie a una Campo de otra Tabla
ALTER TABLE [LUSAX2].[FRENO]
ADD CONSTRAINT FKf_AUTO_ID
FOREIGN KEY (AUTO_ID) REFERENCES [LUSAX2].[AUTOMOVIL](AUTO_ID);

-- Altera La Tabla "MOTOR" para que la FK referencie a una Campo de otra Tabla
ALTER TABLE [LUSAX2].[MOTOR]
ADD CONSTRAINT FKm_AUTO_ID
FOREIGN KEY (AUTO_ID) REFERENCES [LUSAX2].[AUTOMOVIL](AUTO_ID);

-- Altera La Tabla "Telemetria_Freno" para que la FK referencie a una Campo de otra Tabla
ALTER TABLE [LUSAX2].[Telemetria_Freno]
ADD CONSTRAINT FKT_FRENO_NRO_SERIE
FOREIGN KEY (FRENO_NRO_SERIE) REFERENCES [LUSAX2].[Freno](FRENO_NRO_SERIE);

-- Altera La Tabla "Carrera" para que la FK referencie a una Campo de otra Tabla
ALTER TABLE [LUSAX2].[Carrera]
ADD CONSTRAINT FK_Circuito_id
FOREIGN KEY (Circuito_id) REFERENCES [LUSAX2].[Circuito](Circuito_id);


-- Altera La Tabla "Circuito" para que la FK referencie a una Campo de otra Tabla
ALTER TABLE [LUSAX2].[Circuito]
ADD CONSTRAINT FKC_SECTOR_CODIGO
FOREIGN KEY (SECTOR_CODIGO) REFERENCES [LUSAX2].[Sector](SECTOR_CODIGO);

-- Altera La Tabla "Telemetria_CajaDeCambio" para que la FK referencie a una Campo de otra Tabla
ALTER TABLE [LUSAX2].[Telemetria_CajaDeCambio]
ADD CONSTRAINT FKT_CAJA_NRO_SERIE
FOREIGN KEY (CAJA_NRO_SERIE) REFERENCES [LUSAX2].[CajaDeCambio](CAJA_NRO_SERIE);

-- Altera La Tabla "Telemetria_Motor" para que la FK referencie a una Campo de otra Tabla
ALTER TABLE [LUSAX2].[Telemetria_Motor]
ADD CONSTRAINT FKT_MOTOR_NRO_SERIE
FOREIGN KEY (MOTOR_NRO_SERIE) REFERENCES [LUSAX2].[Motor](MOTOR_NRO_SERIE);

-- Inserta en el Esquema LUSAX2 en la Tabla Sector los Campos Correspondientes
INSERT INTO LUSAX2.Sector (SECTOR_CODIGO, SECTOR_TIPO, SECTOR_DISTANCIA)
SELECT DISTINCT CODIGO_SECTOR, SECTO_TIPO, SECTOR_DISTANCIA
FROM gd_esquema.Maestra
ORDER BY CODIGO_SECTOR

-- Inserta en el Esquema LUSAX2 en la Tabla Circuito los Campos Correspondientes
INSERT INTO LUSAX2.Circuito (CIRCUITO_CODIGO, SECTOR_CODIGO, CIRCUITO_NOMBRE, CIRCUITO_PAIS)
SELECT DISTINCT CIRCUITO_CODIGO, em.CODIGO_SECTOR, CIRCUITO_NOMBRE, CIRCUITO_PAIS
FROM gd_esquema.Maestra AS em
JOIN LUSAX2.Sector AS s ON em.CODIGO_SECTOR = s.SECTOR_CODIGO
ORDER BY EM.CIRCUITO_CODIGO,EM.CODIGO_SECTOR

-- Inserta en el Esquema LUSAX2 en la Tabla Carrera los Campos Correspondientes
INSERT INTO LUSAX2.Carrera (CARRERA_CODIGO, Circuito_id, CARRERA_CLIMA, CARRERA_CANT_VUELTAS, CARRERA_FECHA, CARRERA_TOTAL_CARRERA)
SELECT DISTINCT CODIGO_CARRERA, s.Circuito_id, CARRERA_CLIMA, CARRERA_CANT_VUELTAS, CARRERA_FECHA, CARRERA_TOTAL_CARRERA
FROM gd_esquema.Maestra as em 
JOIN LUSAX2.Circuito as s ON em.CODIGO_SECTOR = s.SECTOR_CODIGO 
AND em.CIRCUITO_CODIGO = s.CIRCUITO_CODIGO
ORDER BY CODIGO_CARRERA, S.CIRCUITO_ID

-- Inserta en el Esquema LUSAX2 en la Tabla INCIDENTE los Campos Correspondientes
INSERT INTO LUSAX2.INCIDENTE (carrera_id, INCIDENTE_TIPO, INCIDENTE_BANDERA, INCIDENTE_TIEMPO)
select s.carrera_id, em.INCIDENTE_TIPO, em.INCIDENTE_BANDERA, em.INCIDENTE_TIEMPO
FROM gd_esquema.Maestra AS em 
JOIN LUSAX2.Carrera as s on s.carrera_codigo = em.CODIGO_CARRERA 
AND s.circuito_id = (select Circuito_id 
                     from LUSAX2.Circuito 
					 where SECTOR_CODIGO = CODIGO_SECTOR)
where INCIDENTE_TIPO IS NOT NULL
ORDER BY Carrera_id, INCIDENTE_TIPO

-- Inserta en el Esquema LUSAX2 en la Tabla Escuderia los Campos Correspondientes
INSERT INTO LUSAX2.Escuderia (ESCUDERIA_NOMBRE, ESCUDERIA_NACIONALIDAD)
SELECT DISTINCT ESCUDERIA_NOMBRE, ESCUDERIA_NACIONALIDAD
FROM gd_esquema.Maestra
ORDER BY ESCUDERIA_NACIONALIDAD

-- Inserta en el Esquema LUSAX2 en la Tabla Piloto los Campos Correspondientes
INSERT INTO LUSAX2.Piloto (PILOTO_NOMBRE, PILOTO_APELLIDO, PILOTO_NACIONALIDAD, PILOTO_FECHA_NACIMIENTO)
SELECT DISTINCT PILOTO_NOMBRE, PILOTO_APELLIDO, PILOTO_NACIONALIDAD, PILOTO_FECHA_NACIMIENTO
FROM gd_esquema.Maestra

-- Inserta en el Esquema LUSAX2 en la Tabla Automovil los Campos Correspondientes
INSERT INTO LUSAX2.Automovil (AUTO_NUMERO, AUTO_MODELO, ESCUDERIA_NOMBRE, PILOTO_ID)
SELECT DISTINCT M.AUTO_NUMERO, M.AUTO_MODELO, M.ESCUDERIA_NOMBRE, P.PILOTO_ID
FROM gd_esquema.Maestra AS M 
JOIN LUSAX2.escuderia as e on e.escuderia_nombre=M.escuderia_nombre
JOIN LUSAX2.Piloto AS P ON P.PILOTO_NOMBRE+P.PILOTO_APELLIDO =M.PILOTO_NOMBRE+P.PILOTO_APELLIDO
order by AUTO_NUMERO,AUTO_MODELO

-- Inserta en el Esquema LUSAX2 en la Tabla Neumatico los Campos Correspondientes
INSERT INTO LUSAX2.Neumatico (NEUMATICO_NRO_SERIE, NEUMATICO_POSICION, NEUMATICO_TIPO,AUTO_ID)
SELECT DISTINCT NEUMATICO1_NRO_SERIE_NUEVO, NEUMATICO1_POSICION_NUEVO, NEUMATICO1_TIPO_NUEVO, A.AUTO_ID
FROM gd_esquema.Maestra M 
JOIN LUSAX2.Automovil A ON A.AUTO_NUMERO=M.AUTO_NUMERO 
AND A.AUTO_MODELO=M.AUTO_MODELO
where NEUMATICO1_NRO_SERIE_NUEVO IS NOT NULL
UNION

SELECT DISTINCT NEUMATICO1_NRO_SERIE_VIEJO, NEUMATICO1_POSICION_VIEJO, NEUMATICO1_TIPO_VIEJO,A.AUTO_ID
FROM gd_esquema.Maestra M 
JOIN LUSAX2.Automovil A ON A.AUTO_NUMERO=M.AUTO_NUMERO 
AND A.AUTO_MODELO=M.AUTO_MODELO
where NEUMATICO1_NRO_SERIE_VIEJO IS NOT NULL
UNION

SELECT DISTINCT NEUMATICO2_NRO_SERIE_NUEVO, NEUMATICO2_POSICION_NUEVO, NEUMATICO2_TIPO_NUEVO,A.AUTO_ID
FROM gd_esquema.Maestra M 
JOIN LUSAX2.Automovil A ON A.AUTO_NUMERO=M.AUTO_NUMERO 
AND A.AUTO_MODELO=M.AUTO_MODELO
where NEUMATICO2_NRO_SERIE_NUEVO IS NOT NULL
UNION

SELECT DISTINCT NEUMATICO2_NRO_SERIE_VIEJO, NEUMATICO2_POSICION_VIEJO, NEUMATICO2_TIPO_VIEJO,A.AUTO_ID
FROM gd_esquema.Maestra M 
JOIN LUSAX2.Automovil A ON A.AUTO_NUMERO=M.AUTO_NUMERO 
AND A.AUTO_MODELO=M.AUTO_MODELO
where NEUMATICO2_NRO_SERIE_VIEJO IS NOT NULL
UNION

SELECT DISTINCT NEUMATICO3_NRO_SERIE_NUEVO, NEUMATICO3_POSICION_NUEVO, NEUMATICO3_TIPO_NUEVO,A.AUTO_ID
FROM gd_esquema.Maestra M 
JOIN LUSAX2.Automovil A ON A.AUTO_NUMERO=M.AUTO_NUMERO 
AND A.AUTO_MODELO=M.AUTO_MODELO
where NEUMATICO3_NRO_SERIE_NUEVO IS NOT NULL
UNION

SELECT DISTINCT NEUMATICO3_NRO_SERIE_VIEJO, NEUMATICO3_POSICION_VIEJO, NEUMATICO3_TIPO_VIEJO, A.AUTO_ID
FROM gd_esquema.Maestra M 
JOIN LUSAX2.Automovil A ON A.AUTO_NUMERO=M.AUTO_NUMERO 
AND A.AUTO_MODELO=M.AUTO_MODELO
where NEUMATICO3_NRO_SERIE_VIEJO IS NOT NULL
UNION

SELECT DISTINCT NEUMATICO4_NRO_SERIE_NUEVO, NEUMATICO4_POSICION_NUEVO, NEUMATICO4_TIPO_NUEVO, A.AUTO_ID
FROM gd_esquema.Maestra M 
JOIN LUSAX2.Automovil A ON A.AUTO_NUMERO=M.AUTO_NUMERO 
AND A.AUTO_MODELO=M.AUTO_MODELO
where NEUMATICO4_NRO_SERIE_NUEVO IS NOT NULL
UNION

SELECT DISTINCT NEUMATICO4_NRO_SERIE_VIEJO, NEUMATICO4_POSICION_VIEJO, NEUMATICO4_TIPO_VIEJO, A.AUTO_ID
FROM gd_esquema.Maestra M 
JOIN LUSAX2.Automovil A ON A.AUTO_NUMERO=M.AUTO_NUMERO 
AND A.AUTO_MODELO=M.AUTO_MODELO
where NEUMATICO4_NRO_SERIE_VIEJO IS NOT NULL
order by 1

-- Inserta en el Esquema LUSAX2 en la Tabla Motor los Campos Correspondientes
INSERT INTO LUSAX2.Motor(MOTOR_NRO_SERIE, MOTOR_MODELO,AUTO_ID)
select distinct TELE_MOTOR_NRO_SERIE, TELE_MOTOR_MODELO, A.AUTO_ID
from gd_esquema.Maestra M 
JOIN LUSAX2.Automovil A ON A.AUTO_NUMERO=M.AUTO_NUMERO 
AND A.AUTO_MODELO=M.AUTO_MODELO
WHERE TELE_MOTOR_MODELO IS NOT NULL 
AND TELE_MOTOR_NRO_SERIE IS NOT NULL

-- Inserta en el Esquema LUSAX2 en la Tabla CajaDeCambio los Campos Correspondientes
INSERT INTO LUSAX2.CajaDeCambio (CAJA_NRO_SERIE, CAJA_MODELO, AUTO_ID)
SELECT DISTINCT TELE_CAJA_NRO_SERIE, TELE_MOTOR_MODELO, A.AUTO_ID
FROM gd_esquema.Maestra M 
JOIN LUSAX2.Automovil A ON A.AUTO_NUMERO=M.AUTO_NUMERO 
AND A.AUTO_MODELO=M.AUTO_MODELO
where TELE_CAJA_NRO_SERIE IS NOT NULL 
AND TELE_CAJA_MODELO IS NOT NULL

-- Inserta en el Esquema LUSAX2 en la Tabla Telemetria_CajaDeCambio los Campos Correspondientes
INSERT INTO LUSAX2.Telemetria_CajaDeCambio (CAJA_NRO_SERIE, TELE_CAJA_TEMP_ACEITE, TELE_CAJA_RPM, TELE_CAJA_DESGASTE)
select distinct em.TELE_CAJA_NRO_SERIE,em.TELE_CAJA_TEMP_ACEITE,em.TELE_CAJA_RPM,em.TELE_CAJA_DESGASTE
FROM gd_esquema.Maestra AS em
JOIN LUSAX2.CajaDeCambio AS c ON em.TELE_CAJA_NRO_SERIE = c.CAJA_NRO_SERIE

-- Inserta en el Esquema LUSAX2 en la Tabla Freno los Campos Correspondientes
INSERT INTO LUSAX2.Freno (FRENO_NRO_SERIE, FRENO_POSICION, AUTO_ID)
select distinct TELE_FRENO1_NRO_SERIE,TELE_FRENO1_POSICION,A.AUTO_ID
from gd_esquema.Maestra M 
JOIN LUSAX2.Automovil A ON A.AUTO_NUMERO=M.AUTO_NUMERO 
AND A.AUTO_MODELO=M.AUTO_MODELO
where TELE_FRENO1_NRO_SERIE IS NOT NULL
UNION

select distinct TELE_FRENO2_NRO_SERIE, TELE_FRENO2_POSICION, A.AUTO_ID
from gd_esquema.Maestra M 
JOIN LUSAX2.Automovil A ON A.AUTO_NUMERO=M.AUTO_NUMERO 
AND A.AUTO_MODELO=M.AUTO_MODELO
where TELE_FRENO2_NRO_SERIE IS NOT NULL
UNION

select distinct TELE_FRENO3_NRO_SERIE, TELE_FRENO3_POSICION, A.AUTO_ID
from gd_esquema.Maestra M 
JOIN LUSAX2.Automovil A ON A.AUTO_NUMERO=M.AUTO_NUMERO 
AND A.AUTO_MODELO=M.AUTO_MODELO
where TELE_FRENO3_NRO_SERIE IS NOT NULL
UNION

select distinct TELE_FRENO4_NRO_SERIE, TELE_FRENO4_POSICION, A.AUTO_ID
from gd_esquema.Maestra M 
JOIN LUSAX2.Automovil A ON A.AUTO_NUMERO=M.AUTO_NUMERO 
AND A.AUTO_MODELO=M.AUTO_MODELO
where TELE_FRENO4_NRO_SERIE IS NOT NULL

-- Inserta en el Esquema LUSAX2 en la Tabla Telemetria_Motor los Campos Correspondientes
INSERT INTO LUSAX2.Telemetria_Motor (MOTOR_NRO_SERIE, TELE_MOTOR_RPM, TELE_MOTOR_TEMP_ACEITE, TELE_MOTOR_TEMP_AGUA, TELE_MOTOR_POTENCIA)
select distinct TELE_MOTOR_NRO_SERIE, TELE_MOTOR_RPM, TELE_MOTOR_TEMP_ACEITE, TELE_MOTOR_TEMP_AGUA, TELE_MOTOR_POTENCIA
FROM gd_esquema.Maestra AS em
JOIN LUSAX2.Motor AS m ON em.TELE_MOTOR_NRO_SERIE = m.MOTOR_NRO_SERIE

-- Inserta en el Esquema LUSAX2 en la Tabla Telemetria_Freno los Campos Correspondientes
INSERT INTO LUSAX2.Telemetria_Freno (FRENO_NRO_SERIE, TELE_FRENO_GROSOR_PASTILLA, TELE_TAMANIO_DISCO, TELE_TEMPERATURA)
select distinct TELE_FRENO1_NRO_SERIE, TELE_FRENO1_GROSOR_PASTILLA, TELE_FRENO1_TAMANIO_DISCO, TELE_FRENO1_TEMPERATURA
FROM gd_esquema.Maestra AS em
JOIN LUSAX2.Freno AS f ON em.TELE_FRENO1_NRO_SERIE = f.FRENO_NRO_SERIE
UNION

select distinct TELE_FRENO2_NRO_SERIE, TELE_FRENO2_GROSOR_PASTILLA, TELE_FRENO2_TAMANIO_DISCO, TELE_FRENO2_TEMPERATURA
FROM gd_esquema.Maestra AS em
JOIN LUSAX2.Freno AS f ON em.TELE_FRENO2_NRO_SERIE = f.FRENO_NRO_SERIE
UNION

select distinct TELE_FRENO3_NRO_SERIE, TELE_FRENO3_GROSOR_PASTILLA, TELE_FRENO3_TAMANIO_DISCO, TELE_FRENO3_TEMPERATURA
FROM gd_esquema.Maestra AS em
JOIN LUSAX2.Freno AS f ON em.TELE_FRENO3_NRO_SERIE = f.FRENO_NRO_SERIE
UNION

select distinct TELE_FRENO3_NRO_SERIE, TELE_FRENO3_GROSOR_PASTILLA, TELE_FRENO3_TAMANIO_DISCO, TELE_FRENO3_TEMPERATURA
FROM gd_esquema.Maestra AS em
JOIN LUSAX2.Freno AS f ON em.TELE_FRENO4_NRO_SERIE = f.FRENO_NRO_SERIE

-- Inserta en el Esquema LUSAX2 en la Tabla Telemetria_Neumatico los Campos Correspondientes
INSERT INTO LUSAX2.Telemetria_Neumatico (NEUMATICO_NRO_SERIE, TELE_NEUMATICO_PRESION, TELE_NEUMATICO_PROFUNDIDAD, TELE_NEUMATICO_TEMPERATURA)
select distinct TELE_NEUMATICO1_NRO_SERIE,TELE_NEUMATICO1_PRESION,TELE_NEUMATICO1_PROFUNDIDAD,TELE_NEUMATICO1_TEMPERATURA
FROM gd_esquema.Maestra AS em
JOIN LUSAX2.Neumatico AS N ON em.TELE_NEUMATICO1_NRO_SERIE = N.NEUMATICO_NRO_SERIE
UNION

select distinct TELE_NEUMATICO2_NRO_SERIE, TELE_NEUMATICO2_PRESION, TELE_NEUMATICO2_PROFUNDIDAD, TELE_NEUMATICO2_TEMPERATURA
FROM gd_esquema.Maestra AS em
JOIN LUSAX2.Neumatico AS N ON em.TELE_NEUMATICO2_NRO_SERIE = N.NEUMATICO_NRO_SERIE
UNION

select distinct TELE_NEUMATICO3_NRO_SERIE, TELE_NEUMATICO3_PRESION, TELE_NEUMATICO3_PROFUNDIDAD, TELE_NEUMATICO3_TEMPERATURA
FROM gd_esquema.Maestra AS em
JOIN LUSAX2.Neumatico AS N ON em.TELE_NEUMATICO3_NRO_SERIE = N.NEUMATICO_NRO_SERIE
UNION

select distinct TELE_NEUMATICO4_NRO_SERIE, TELE_NEUMATICO4_PRESION, TELE_NEUMATICO4_PROFUNDIDAD, TELE_NEUMATICO4_TEMPERATURA
FROM gd_esquema.Maestra AS em
JOIN LUSAX2.Neumatico AS N ON em.TELE_NEUMATICO4_NRO_SERIE = N.NEUMATICO_NRO_SERIE
ORDER BY 1,2

-- Inserta en el Esquema LUSAX2 en la Tabla AutoxIncidente los Campos Correspondientes
INSERT INTO LUSAX2.AutoxIncidente (AUTO_ID,INCIDENTE_NUMERO_VUELTA)
SELECT DISTINCT A.AUTO_ID,M.INCIDENTE_NUMERO_VUELTA
FROM gd_esquema.Maestra AS M 
JOIN LUSAX2.Automovil A ON A.AUTO_NUMERO=M.AUTO_NUMERO 
AND A.AUTO_MODELO=M.AUTO_MODELO
WHERE INCIDENTE_NUMERO_VUELTA IS NOT NULL
ORDER BY AUTO_ID

-- Inserta en el Esquema LUSAX2 en la Tabla Telemetria_Auto los Campos Correspondientes
INSERT INTO LUSAX2.Telemetria_Auto (TELE_AUTO_ID, AUTO_ID, TELE_AUTO_COMBUSTIBLE, TELE_AUTO_DISTANCIA_CARRERA, TELE_AUTO_DISTANCIA_VUELTA,
									TELE_AUTO_NRO_VUELTA, TELE_AUTO_POSICION, TELE_AUTO_TIEMPO_VUELTA, TELE_AUTO_VELOCIDAD)
SELECT DISTINCT m.TELE_AUTO_CODIGO, A.AUTO_ID, M.TELE_AUTO_COMBUSTIBLE, M.TELE_AUTO_DISTANCIA_CARRERA, M.TELE_AUTO_DISTANCIA_VUELTA,
				M.TELE_AUTO_NUMERO_VUELTA, M.TELE_AUTO_POSICION, TELE_AUTO_TIEMPO_VUELTA, TELE_AUTO_VELOCIDAD
FROM gd_esquema.Maestra AS M 
JOIN LUSAX2.Automovil A ON A.AUTO_NUMERO = M.AUTO_NUMERO 
AND A.AUTO_MODELO = M.AUTO_MODELO
WHERE TELE_AUTO_COMBUSTIBLE IS NOT NULL
order by AUTO_ID, TELE_AUTO_POSICION, TELE_AUTO_NUMERO_VUELTA

-- Inserta en el Esquema LUSAX2 en la Tabla Parada los Campos Correspondientes
INSERT INTO LUSAX2.Parada (carrera_id, auto_id, [PARADA_BOX_VUELTA], [PARADA_BOX_TIEMPO])
select distinct c.carrera_id, a.auto_id,[PARADA_BOX_VUELTA], [PARADA_BOX_TIEMPO]
FROM gd_esquema.Maestra AS em
JOIN LUSAX2.automovil as a on a.auto_id = (select distinct auto_id
                                           from LUSAX2.Automovil
										   where LUSAX2.automovil.auto_numero = em.[AUTO_NUMERO]
										   AND LUSAX2.automovil.AUTO_MODELO = em.auto_Modelo)
JOIN LUSAX2.Carrera As c ON  c.carrera_id = (select distinct carrera_id 
                                             from LUSAX2.Carrera
											 where carrera_codigo = CODIGO_CARRERA
											 AND circuito_id = (select Circuito_id 
											                    from LUSAX2.Circuito 
																where [SECTOR_CODIGO] = em.[CODIGO_SECTOR]))
where PARADA_BOX_TIEMPO IS NOT NULL
order by AUTO_ID,Carrera_id

-- Inserta en el Esquema LUSAX2 en la Tabla Cambio_Neumatico los Campos Correspondientes
INSERT INTO LUSAX2.Cambio_Neumatico (NEUMATICO_NRO_SERIE_VIEJO,NEUMATICO_NRO_SERIE_NUEVO,PARADA_CODIGO_BOX)
select distinct em.NEUMATICO1_NRO_SERIE_VIEJO, em.NEUMATICO1_NRO_SERIE_NUEVO, p.PARADA_CODIGO_BOX
FROM gd_esquema.Maestra AS em
JOIN LUSAX2.Parada p ON p.PARADA_BOX_TIEMPO+p.PARADA_BOX_VUELTA=em.PARADA_BOX_TIEMPO+em.PARADA_BOX_VUELTA
where NEUMATICO1_NRO_SERIE_NUEVO IS NOT NULL
union

select distinct em.NEUMATICO2_NRO_SERIE_VIEJO, em.NEUMATICO2_NRO_SERIE_NUEVO, p.PARADA_CODIGO_BOX
FROM gd_esquema.Maestra AS em
JOIN LUSAX2.Parada p ON p.PARADA_BOX_TIEMPO+p.PARADA_BOX_VUELTA=em.PARADA_BOX_TIEMPO+em.PARADA_BOX_VUELTA
where NEUMATICO2_NRO_SERIE_NUEVO IS NOT NULL
union

select distinct em.NEUMATICO3_NRO_SERIE_VIEJO, em.NEUMATICO3_NRO_SERIE_NUEVO, p.PARADA_CODIGO_BOX
FROM gd_esquema.Maestra AS em
JOIN LUSAX2.Parada p ON p.PARADA_BOX_TIEMPO+p.PARADA_BOX_VUELTA=em.PARADA_BOX_TIEMPO+em.PARADA_BOX_VUELTA
where NEUMATICO3_NRO_SERIE_NUEVO IS NOT NULL
union

select distinct em.NEUMATICO4_NRO_SERIE_VIEJO, em.NEUMATICO4_NRO_SERIE_NUEVO, p.PARADA_CODIGO_BOX
FROM gd_esquema.Maestra AS em
JOIN LUSAX2.Parada p ON p.PARADA_BOX_TIEMPO+p.PARADA_BOX_VUELTA=em.PARADA_BOX_TIEMPO+em.PARADA_BOX_VUELTA
where NEUMATICO4_NRO_SERIE_NUEVO IS NOT NULL

-- Inserta en el Esquema LUSAX2 en la Tabla Telemetria los Campos Correspondientes
insert into LUSAX2.Telemetria (TELE_AUTO_ID, carrera_id, sector_codigo, TELE_CAJA_CAMBIO_ID, TELE_MOTOR_ID)
select DISTINCT TELE_AUTO_CODIGO, c.carrera_id,codigo_sector, tc.TELE_CAJA_CAMBIO_ID, tm.TELE_MOTOR_ID
from gd_esquema.Maestra as em								   
JOIN LUSAX2.Carrera As c ON  c.carrera_id = (select distinct carrera_id 
                                             from LUSAX2.Carrera
											 where carrera_codigo = CODIGO_CARRERA
											 AND circuito_id = (select Circuito_id 
											                    from LUSAX2.Circuito 
																where [SECTOR_CODIGO] = em.[CODIGO_SECTOR]))
JOIN LUSAX2.Telemetria_CajaDeCambio As tc on tc.TELE_CAJA_CAMBIO_ID = (select TELE_CAJA_CAMBIO_ID
                                                                       from LUSAX2.Telemetria_CajaDeCambio
																	   where LUSAX2.Telemetria_CajaDeCambio.CAJA_NRO_SERIE = em.TELE_CAJA_NRO_SERIE
																	   AND LUSAX2.Telemetria_CajaDeCambio.tele_caja_temp_aceite = em.TELE_CAJA_TEMP_ACEITE
																	   AND LUSAX2.Telemetria_CajaDeCambio.TELE_CAJA_RPM = em.TELE_CAJA_RPM
																	   AND LUSAX2.Telemetria_CajaDeCambio.tele_caja_desgaste = em.TELE_CAJA_DESGASTE)
JOIN LUSAX2.Telemetria_Motor As tm on tm.TELE_MOTOR_ID = (select TELE_MOTOR_ID
                                                          from LUSAX2.Telemetria_Motor
														  where LUSAX2.Telemetria_Motor.MOTOR_NRO_SERIE = em.TELE_MOTOR_NRO_SERIE
														  AND LUSAX2.Telemetria_Motor.TELE_MOTOR_RPM = em.TELE_MOTOR_RPM
														  AND LUSAX2.Telemetria_Motor.TELE_MOTOR_TEMP_ACEITE = em.TELE_MOTOR_TEMP_ACEITE
														  AND LUSAX2.Telemetria_Motor.TELE_MOTOR_TEMP_AGUA = em.TELE_MOTOR_TEMP_AGUA
														  AND LUSAX2.Telemetria_Motor.TELE_MOTOR_POTENCIA = em.TELE_MOTOR_POTENCIA)

