USE test
go


-- Sector
INSERT INTO test.LUSAX2.Sector (SECTOR_CODIGO, SECTOR_TIPO, SECTOR_DISTANCIA)
SELECT DISTINCT CODIGO_SECTOR ,SECTO_TIPO, SECTOR_DISTANCIA
FROM GD1C2022.gd_esquema.Maestra
ORDER BY CODIGO_SECTOR

-- ESCUDERIA
INSERT INTO test.LUSAX2.Escuderia (ESCUDERIA_NOMBRE, ESCUDERIA_NACIONALIDAD)
SELECT DISTINCT ESCUDERIA_NOMBRE, ESCUDERIA_NACIONALIDAD
FROM GD1C2022.gd_esquema.Maestra

-- PILOTO
INSERT INTO test.LUSAX2.Piloto (PILOTO_NOMBRE, PILOTO_APELLIDO, PILOTO_NACIONALIDAD, PILOTO_FECHA_NACIMIENTO)
SELECT DISTINCT PILOTO_NOMBRE, PILOTO_APELLIDO ,PILOTO_NACIONALIDAD,PILOTO_FECHA_NACIMIENTO
FROM GD1C2022.gd_esquema.Maestra

--NEUMATICO
INSERT INTO test.LUSAX2.Neumatico(NEUMATICO_NRO_SERIE,NEUMATICO_POSICION,NEUMATICO_TIPO)
SELECT DISTINCT NEUMATICO1_NRO_SERIE_NUEVO,NEUMATICO1_POSICION_NUEVO,NEUMATICO1_TIPO_NUEVO
FROM GD1C2022.gd_esquema.Maestra
UNION
SELECT DISTINCT NEUMATICO1_NRO_SERIE_VIEJO,NEUMATICO1_POSICION_VIEJO,NEUMATICO1_TIPO_VIEJO
FROM GD1C2022.gd_esquema.Maestra
UNION
SELECT DISTINCT NEUMATICO2_NRO_SERIE_NUEVO,NEUMATICO2_POSICION_NUEVO,NEUMATICO2_TIPO_NUEVO
FROM GD1C2022.gd_esquema.Maestra
UNION
SELECT DISTINCT NEUMATICO2_NRO_SERIE_VIEJO,NEUMATICO2_POSICION_VIEJO,NEUMATICO2_TIPO_VIEJO
FROM GD1C2022.gd_esquema.Maestra
UNION
SELECT DISTINCT NEUMATICO3_NRO_SERIE_NUEVO,NEUMATICO3_POSICION_NUEVO,NEUMATICO3_TIPO_NUEVO
FROM GD1C2022.gd_esquema.Maestra
UNION
SELECT DISTINCT NEUMATICO3_NRO_SERIE_VIEJO,NEUMATICO3_POSICION_VIEJO,NEUMATICO3_TIPO_VIEJO
FROM GD1C2022.gd_esquema.Maestra
UNION
SELECT DISTINCT NEUMATICO4_NRO_SERIE_NUEVO,NEUMATICO4_POSICION_NUEVO,NEUMATICO4_TIPO_NUEVO
FROM GD1C2022.gd_esquema.Maestra
UNION
SELECT DISTINCT NEUMATICO4_NRO_SERIE_VIEJO,NEUMATICO4_POSICION_VIEJO,NEUMATICO4_TIPO_VIEJO
FROM GD1C2022.gd_esquema.Maestra
order by 1

--hasta aca copia bien


/*--CARRERA
INSERT INTO test.LUSAX2.Carrera (CARRERA_CODIGO, CIRCUITO_CODIGO, CARRERA_CLIMA, CARRERA_CANT_VUELTAS,CARRERA_FECHA)
SELECT DISTINCT CODIGO_CARRERA, CIRCUITO_CODIGO, CARRERA_CLIMA, CARRERA_CANT_VUELTAS, CARRERA_FECHA
FROM GD1C2022.gd_esquema.Maestra
ORDER BY CODIGO_CARRERA
*/
/*
-- CIRCUITO
INSERT INTO test.LUSAX2.Circuito (CIRCUITO_CODIGO, SECTOR_CODIGO, CIRCUITO_NOMBRE, CIRCUITO_PAIS)
SELECT DISTINCT CIRCUITO_CODIGO, s.SECTOR_CODIGO, CIRCUITO_NOMBRE, CIRCUITO_PAIS
FROM GD1C2022.gd_esquema.Maestra AS em
JOIN LUSAX2.Sector AS s ON em.CODIGO_SECTOR = s.SECTOR_CODIGO*/
/*
-- AUTO --- FALTA TERMINAR
INSERT INTO LUSAX2.Automovil (AUTO_NUMERO, ESCUDERIA_NOMBRE, PILOTO_ID,NEUMATICO_NRO_SERIE, MOTOR_NRO_SERIE, CAJA_NRO_SERIE, FRENO_NRO_SERIE, AUTO_MODELO)
SELECT DISTINCT M.AUTO_NUMERO,E.ESCUDERIA_NOMBRE,P.PILOTO_ID,N.NEUMATICO_NRO_SERIE,M.MOTOR_NRO_SERIE,C.CAJA_NRO_SERIE,F.FRENO_NRO_SERIE,M.AUTO_MODELO
FROM gd_esquema.Maestra AS M
JOIN LUSAX2.Piloto AS P ON P.PILOTO_ID = 

*/
select * from LUSAX2.Neumatico
select NEUMATICO1_NRO_SERIE_NUEVO,NEUMATICO1_POSICION_NUEVO,NEUMATICO1_TIPO_NUEVO from GD1C2022.gd_esquema.Maestra

